config/routes.rb
Registrator::Application.routes.draw do
  resources :clients

  resources :orders

  resources :applies

end

app/models/apply.rb
class Apply < ActiveRecord::Base
	belongs_to :apply_status, foreign_key: "phoneApplyStatus"
	belongs_to :apply_status, foreign_key: "internetApplyStatus"
	belongs_to :apply_status, foreign_key: "iptvApplyStatus"
	belongs_to :client_type

	#checks the obligatory presence of data in some columns
	validates :applyNumber, :nameOrFIO, :street, :house, :applyTreatedBy,
	  :phoneContractConcludedBy, :internetContractConcludedBy, 
	  :iptvContractConcludedBy, :clientType_id, :insertionDate, :phoneApplyStatus,
	  :internetApplyStatus, :iptvApplyStatus, presence: true
	 #checks uniqueness of some columns
	 validates :applyNumber, uniqueness: true
	 #checks if incoming data equal string from array
	 validates :phoneApplyStatus, inclusion: { in: 1..6 }
	 validates :internetApplyStatus, inclusion: { in: 1..6 }
	 validates :iptvApplyStatus, inclusion: { in: 1..6 }
	 validates :clientType_id, inclusion: { in: 1..5 }
end

app/controllers/applies_controller.rb
class AppliesController < ApplicationController
  before_action :set_apply, only: [:show, :edit, :update, :destroy]

  # GET /applies
  # GET /applies.json
  def index
    @applies = Apply.all
  end

  # GET /applies/1
  # GET /applies/1.json
  def show
  end

  # GET /applies/new
  def new
    @apply = Apply.new
  end

  # GET /applies/1/edit
  def edit
  end

  # POST /applies
  # POST /applies.json
  def create
    @apply = Apply.new(apply_params)

    respond_to do |format|
      if @apply.save
        format.html { redirect_to @apply, notice: 'Apply was successfully created.' }
        format.json { render action: 'show', status: :created, location: @apply }
      else
        format.html { render action: 'new' }
        format.json { render json: @apply.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applies/1
  # PATCH/PUT /applies/1.json
  def update
    respond_to do |format|
      if @apply.update(apply_params)
        format.html { redirect_to @apply, notice: 'Apply was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @apply.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applies/1
  # DELETE /applies/1.json
  def destroy
    @apply.destroy
    respond_to do |format|
      format.html { redirect_to applies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apply
      @apply = Apply.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def apply_params
      params.require(:apply).permit(:applyNumber, :phoneApplyDate, :internetApplyDate, :iptvApplyDate, :nameOrFIO, :street, :house, :building, :apartmentOrOffice, :floor, :entrance, :phoneApplyStatus, :internetApplyStatus, :iptvApplyStatus, :applyTreatedBy, :plannedPhoneInstallDate, :plannedInternetInstallDate, :phoneComments, :internetComments, :phoneContractNumber, :phoneContractDate, :phonePorts, :phoneContractConcludedBy, :phonePaymentDate, :phoneDocsPassDate, :phoneInstallDate, :internetContractNumber, :internetContractDate, :internetPorts, :internetContractConcludedBy, :internetPaymentDate, :internetDocsPassDate, :internetInstallDate, :iptvContractNumber, :iptvContractDate, :iptvPorts, :iptvContractConcludedBy, :iptvPaymentDate, :iptvInstallDate, :setToBox, :clientType_id, :insertionDate)
    end
end

app/helpers/applies_helper.rb
module AppliesHelper
end

app/views/applies/_form.html.erb
<%= form_for(@apply) do |f| %>
  <% if @apply.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@apply.errors.count, "error") %> prohibited this apply from being saved:</h2>

      <ul>
      <% @apply.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :applyNumber %><br>
    <%= f.number_field :applyNumber %>
  </div>
  <div class="field">
    <%= f.label :phoneApplyDate %><br>
    <%= f.date_select :phoneApplyDate %>
  </div>
  <div class="field">
    <%= f.label :internetApplyDate %><br>
    <%= f.date_select :internetApplyDate %>
  </div>
  <div class="field">
    <%= f.label :iptvApplyDate %><br>
    <%= f.date_select :iptvApplyDate %>
  </div>
  <div class="field">
    <%= f.label :nameOrFIO %><br>
    <%= f.text_area :nameOrFIO %>
  </div>
  <div class="field">
    <%= f.label :street %><br>
    <%= f.text_area :street %>
  </div>
  <div class="field">
    <%= f.label :house %><br>
    <%= f.number_field :house %>
  </div>
  <div class="field">
    <%= f.label :building %><br>
    <%= f.text_area :building %>
  </div>
  <div class="field">
    <%= f.label :apartmentOrOffice %><br>
    <%= f.number_field :apartmentOrOffice %>
  </div>
  <div class="field">
    <%= f.label :floor %><br>
    <%= f.number_field :floor %>
  </div>
  <div class="field">
    <%= f.label :entrance %><br>
    <%= f.number_field :entrance %>
  </div>
  <div class="field">
    <%= f.label :phoneApplyStatus %><br>
    <%= f.number_field :phoneApplyStatus %>
  </div>
  <div class="field">
    <%= f.label :internetApplyStatus %><br>
    <%= f.number_field :internetApplyStatus %>
  </div>
  <div class="field">
    <%= f.label :iptvApplyStatus %><br>
    <%= f.number_field :iptvApplyStatus %>
  </div>
  <div class="field">
    <%= f.label :applyTreatedBy %><br>
    <%= f.text_area :applyTreatedBy %>
  </div>
  <div class="field">
    <%= f.label :plannedPhoneInstallDate %><br>
    <%= f.date_select :plannedPhoneInstallDate %>
  </div>
  <div class="field">
    <%= f.label :plannedInternetInstallDate %><br>
    <%= f.date_select :plannedInternetInstallDate %>
  </div>
  <div class="field">
    <%= f.label :phoneComments %><br>
    <%= f.text_area :phoneComments %>
  </div>
  <div class="field">
    <%= f.label :internetComments %><br>
    <%= f.text_area :internetComments %>
  </div>
  <div class="field">
    <%= f.label :phoneContractNumber %><br>
    <%= f.number_field :phoneContractNumber %>
  </div>
  <div class="field">
    <%= f.label :phoneContractDate %><br>
    <%= f.date_select :phoneContractDate %>
  </div>
  <div class="field">
    <%= f.label :phonePorts %><br>
    <%= f.number_field :phonePorts %>
  </div>
  <div class="field">
    <%= f.label :phoneContractConcludedBy %><br>
    <%= f.text_area :phoneContractConcludedBy %>
  </div>
  <div class="field">
    <%= f.label :phonePaymentDate %><br>
    <%= f.date_select :phonePaymentDate %>
  </div>
  <div class="field">
    <%= f.label :phoneDocsPassDate %><br>
    <%= f.date_select :phoneDocsPassDate %>
  </div>
  <div class="field">
    <%= f.label :phoneInstallDate %><br>
    <%= f.date_select :phoneInstallDate %>
  </div>
  <div class="field">
    <%= f.label :internetContractNumber %><br>
    <%= f.number_field :internetContractNumber %>
  </div>
  <div class="field">
    <%= f.label :internetContractDate %><br>
    <%= f.date_select :internetContractDate %>
  </div>
  <div class="field">
    <%= f.label :internetPorts %><br>
    <%= f.number_field :internetPorts %>
  </div>
  <div class="field">
    <%= f.label :internetContractConcludedBy %><br>
    <%= f.text_area :internetContractConcludedBy %>
  </div>
  <div class="field">
    <%= f.label :internetPaymentDate %><br>
    <%= f.date_select :internetPaymentDate %>
  </div>
  <div class="field">
    <%= f.label :internetDocsPassDate %><br>
    <%= f.date_select :internetDocsPassDate %>
  </div>
  <div class="field">
    <%= f.label :internetInstallDate %><br>
    <%= f.date_select :internetInstallDate %>
  </div>
  <div class="field">
    <%= f.label :iptvContractNumber %><br>
    <%= f.number_field :iptvContractNumber %>
  </div>
  <div class="field">
    <%= f.label :iptvContractDate %><br>
    <%= f.date_select :iptvContractDate %>
  </div>
  <div class="field">
    <%= f.label :iptvPorts %><br>
    <%= f.number_field :iptvPorts %>
  </div>
  <div class="field">
    <%= f.label :iptvContractConcludedBy %><br>
    <%= f.text_area :iptvContractConcludedBy %>
  </div>
  <div class="field">
    <%= f.label :iptvPaymentDate %><br>
    <%= f.date_select :iptvPaymentDate %>
  </div>
  <div class="field">
    <%= f.label :iptvInstallDate %><br>
    <%= f.date_select :iptvInstallDate %>
  </div>
  <div class="field">
    <%= f.label :setToBox %><br>
    <%= f.check_box :setToBox %>
  </div>
  <div class="field">
    <%= f.label :clientType %><br>
    <%= f.number_field :clientType_id %>
  </div>
  <div class="field">
    <%= f.label :insertionDate %><br>
    <%= f.date_select :insertionDate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/applies/edit.html.erb
<h1>Editing apply</h1>

<%= render 'form' %>

<%= link_to 'Show', @apply %> |
<%= link_to 'Back', applies_path %>

app/views/applies/index.html.erb
<h1>Listing applies</h1>

<table>
  <thead>
    <tr>
      <th>Applynumber</th>
      <th>Phoneapplydate</th>
      <th>Internetapplydate</th>
      <th>Iptvapplydate</th>
      <th>Nameorfio</th>
      <th>Street</th>
      <th>House</th>
      <th>Building</th>
      <th>Apartmentoroffice</th>
      <th>Floor</th>
      <th>Entrance</th>
      <th>Phoneapplystatus</th>
      <th>Internetapplystatus</th>
      <th>Iptvapplystatus</th>
      <th>Applytreatedby</th>
      <th>Plannedphoneinstalldate</th>
      <th>Plannedinternetinstalldate</th>
      <th>Phonecomments</th>
      <th>Internetcomments</th>
      <th>Phonecontractnumber</th>
      <th>Phonecontractdate</th>
      <th>Phoneports</th>
      <th>Phonecontractconcludedby</th>
      <th>Phonepaymentdate</th>
      <th>Phonedocspassdate</th>
      <th>Phoneinstalldate</th>
      <th>Internetcontractnumber</th>
      <th>Internetcontractdate</th>
      <th>Internetports</th>
      <th>Internetcontractconcludedby</th>
      <th>Internetpaymentdate</th>
      <th>Internetdocspassdate</th>
      <th>Internetinstalldate</th>
      <th>Iptvcontractnumber</th>
      <th>Iptvcontractdate</th>
      <th>Iptvports</th>
      <th>Iptvcontractconcludedby</th>
      <th>Iptvpaymentdate</th>
      <th>Iptvinstalldate</th>
      <th>Settobox</th>
      <th>Clienttype_id</th>
      <th>Insertiondate</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @applies.each do |apply| %>
      <tr<%= cycle(" class=\"grey_row\"".html_safe, nil) %>>
        <td><%= apply.applyNumber %></td>
        <td><%= apply.phoneApplyDate %></td>
        <td><%= apply.internetApplyDate %></td>
        <td><%= apply.iptvApplyDate %></td>
        <td><%= apply.nameOrFIO %></td>
        <td><%= apply.street %></td>
        <td><%= apply.house %></td>
        <td><%= apply.building %></td>
        <td><%= apply.apartmentOrOffice %></td>
        <td><%= apply.floor %></td>
        <td><%= apply.entrance %></td>
        <td><%= ApplyStatus.find(apply.phoneApplyStatus).status %></td>
        <td><%= ApplyStatus.find(apply.internetApplyStatus).status %></td>
        <td><%= ApplyStatus.find(apply.iptvApplyStatus).status %></td>
        <td><%= apply.applyTreatedBy %></td>
        <td><%= apply.plannedPhoneInstallDate %></td>
        <td><%= apply.plannedInternetInstallDate %></td>
        <td><%= apply.phoneComments %></td>
        <td><%= apply.internetComments %></td>
        <td><%= apply.phoneContractNumber %></td>
        <td><%= apply.phoneContractDate %></td>
        <td><%= apply.phonePorts %></td>
        <td><%= apply.phoneContractConcludedBy %></td>
        <td><%= apply.phonePaymentDate %></td>
        <td><%= apply.phoneDocsPassDate %></td>
        <td><%= apply.phoneInstallDate %></td>
        <td><%= apply.internetContractNumber %></td>
        <td><%= apply.internetContractDate %></td>
        <td><%= apply.internetPorts %></td>
        <td><%= apply.internetContractConcludedBy %></td>
        <td><%= apply.internetPaymentDate %></td>
        <td><%= apply.internetDocsPassDate %></td>
        <td><%= apply.internetInstallDate %></td>
        <td><%= apply.iptvContractNumber %></td>
        <td><%= apply.iptvContractDate %></td>
        <td><%= apply.iptvPorts %></td>
        <td><%= apply.iptvContractConcludedBy %></td>
        <td><%= apply.iptvPaymentDate %></td>
        <td><%= apply.iptvInstallDate %></td>
        <td><%= apply.setToBox %></td>
        <td><%= ClientType.find(apply.clientType_id).client %></td>
        <td><%= apply.insertionDate %></td>
        <td><%= link_to 'Show', apply %></td>
        <td><%= link_to 'Edit', edit_apply_path(apply) %></td>
        <td><%= link_to 'Destroy', apply, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Apply', new_apply_path %>

app/views/applies/new.html.erb
<h1>New apply</h1>

<%= render 'form' %>

<%= link_to 'Back', applies_path %>

app/views/applies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Applynumber:</strong>
  <%= @apply.applyNumber %>
</p>

<p>
  <strong>Phoneapplydate:</strong>
  <%= @apply.phoneApplyDate %>
</p>

<p>
  <strong>Internetapplydate:</strong>
  <%= @apply.internetApplyDate %>
</p>

<p>
  <strong>Iptvapplydate:</strong>
  <%= @apply.iptvApplyDate %>
</p>

<p>
  <strong>Nameorfio:</strong>
  <%= @apply.nameOrFIO %>
</p>

<p>
  <strong>Street:</strong>
  <%= @apply.street %>
</p>

<p>
  <strong>House:</strong>
  <%= @apply.house %>
</p>

<p>
  <strong>Building:</strong>
  <%= @apply.building %>
</p>

<p>
  <strong>Apartmentoroffice:</strong>
  <%= @apply.apartmentOrOffice %>
</p>

<p>
  <strong>Floor:</strong>
  <%= @apply.floor %>
</p>

<p>
  <strong>Entrance:</strong>
  <%= @apply.entrance %>
</p>

<p>
  <strong>Phoneapplystatus:</strong>
  <%= ApplyStatus.find(@apply.phoneApplyStatus).status %>
</p>

<p>
  <strong>Internetapplystatus:</strong>
  <%= ApplyStatus.find(@apply.internetApplyStatus).status %>
</p>

<p>
  <strong>Iptvapplystatus:</strong>
  <%= ApplyStatus.find(@apply.iptvApplyStatus).status %>
</p>

<p>
  <strong>Applytreatedby:</strong>
  <%= @apply.applyTreatedBy %>
</p>

<p>
  <strong>Plannedphoneinstalldate:</strong>
  <%= @apply.plannedPhoneInstallDate %>
</p>

<p>
  <strong>Plannedinternetinstalldate:</strong>
  <%= @apply.plannedInternetInstallDate %>
</p>

<p>
  <strong>Phonecomments:</strong>
  <%= @apply.phoneComments %>
</p>

<p>
  <strong>Internetcomments:</strong>
  <%= @apply.internetComments %>
</p>

<p>
  <strong>Phonecontractnumber:</strong>
  <%= @apply.phoneContractNumber %>
</p>

<p>
  <strong>Phonecontractdate:</strong>
  <%= @apply.phoneContractDate %>
</p>

<p>
  <strong>Phoneports:</strong>
  <%= @apply.phonePorts %>
</p>

<p>
  <strong>Phonecontractconcludedby:</strong>
  <%= @apply.phoneContractConcludedBy %>
</p>

<p>
  <strong>Phonepaymentdate:</strong>
  <%= @apply.phonePaymentDate %>
</p>

<p>
  <strong>Phonedocspassdate:</strong>
  <%= @apply.phoneDocsPassDate %>
</p>

<p>
  <strong>Phoneinstalldate:</strong>
  <%= @apply.phoneInstallDate %>
</p>

<p>
  <strong>Internetcontractnumber:</strong>
  <%= @apply.internetContractNumber %>
</p>

<p>
  <strong>Internetcontractdate:</strong>
  <%= @apply.internetContractDate %>
</p>

<p>
  <strong>Internetports:</strong>
  <%= @apply.internetPorts %>
</p>

<p>
  <strong>Internetcontractconcludedby:</strong>
  <%= @apply.internetContractConcludedBy %>
</p>

<p>
  <strong>Internetpaymentdate:</strong>
  <%= @apply.internetPaymentDate %>
</p>

<p>
  <strong>Internetdocspassdate:</strong>
  <%= @apply.internetDocsPassDate %>
</p>

<p>
  <strong>Internetinstalldate:</strong>
  <%= @apply.internetInstallDate %>
</p>

<p>
  <strong>Iptvcontractnumber:</strong>
  <%= @apply.iptvContractNumber %>
</p>

<p>
  <strong>Iptvcontractdate:</strong>
  <%= @apply.iptvContractDate %>
</p>

<p>
  <strong>Iptvports:</strong>
  <%= @apply.iptvPorts %>
</p>

<p>
  <strong>Iptvcontractconcludedby:</strong>
  <%= @apply.iptvContractConcludedBy %>
</p>

<p>
  <strong>Iptvpaymentdate:</strong>
  <%= @apply.iptvPaymentDate %>
</p>

<p>
  <strong>Iptvinstalldate:</strong>
  <%= @apply.iptvInstallDate %>
</p>

<p>
  <strong>Settobox:</strong>
  <%= @apply.setToBox %>
</p>

<p>
  <strong>Clienttype_id:</strong>
  <%= ClientType.find(@apply.clientType_id).client %>
</p>

<p>
  <strong>Insertiondate:</strong>
  <%= @apply.insertionDate %>
</p>

<%= link_to 'Edit', edit_apply_path(@apply) %> |
<%= link_to 'Back', applies_path %>